services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgresql://user:password@postgres/mydatabase"
    healthCheckPath: "/"
    plan: free

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    healthCheckPath: "/"
    plan: free
