services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://user:password@mydatabase.internal:5432/mydatabase"
    healthCheckPath: "/"
    plan: free

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: "streamlit run Home.py"
    healthCheckPath: "/"
    plan: free
